export const BASE_API_URL = process.env.NEXT_PUBLIC_BASE_API_URL;

export const ENDPOINT = {
  IDENTITY: {
    ACCEPT_INVITATION: 'identity/accept-invitation',
    LOGIN: 'identity/sign-in',
    LOGIN_GOOGLE: 'identity/sign-in-google',
    PROFILE: 'identity/me',
    REFRESH: 'identity/refresh',
    SWITCH_ORG: 'identity/select-organization',
    FORGOT_PASSWORD: {
      COMPLETE: 'identity/forgot-password/complete',
      REQUEST: 'identity/forgot-password/request',
      VALIDATE: 'identity/forgot-password/validate',
    },
    RESET_PASSWORD: 'identity/reset-password',
    USER_ACTIVATION: 'identity/activation',
  },
  USER_MGMT: {
    USERS: 'user-management/users',
    USERS_BY_ID: (id: string) => `user-management/users/${id}`,
    SCOPES: 'user-management/users/application-scopes',
    RESET_PASSWORD: (id: string) => `user-management/users/${id}/sent-reset-password`,
    RESEND_ACTIVATION: (id: string) => `user-management/users/${id}/resend-activation`,
  },
  EMPLOYEE_MGMT: {
    EMPLOYEE: 'employee-management/employees',
    EMPLOYEE_BY_ID: (id: string) => `employee-management/employees/${id}`,
    EMPLOYEE_EXPORT: 'employee-management/employees/export',
    LEVEL_SEARCH: 'employee-management/levels/search',
    DIVISION_SEARCH: 'employee-management/divisions/search',
    ORGANIZATION_SEARCH: 'employee-management/organizations/search',
    POSITION_SEARCH: 'employee-management/positions/search',
    STATUS_SEARCH: 'employee-management/employment-statuses/search',
    STRUCTURAL_SEARCH: 'employee-management/structural/search',
    USER_SEARCH: 'employee-management/users/search',
    USER_SEARCH_ALL: 'employee-management/users/search-all',
    BANK_SEARCH: 'employee-management/bank-codes/search',
    STATUS_SEARCH_NORESIGN: 'employee-management/employment-statuses-without-resign/search',
    EMPLOYEE_RESIGNS: 'employee-management/employee-resigns',
    EMPLOYEE_SEARCH_APPROVE: 'employee-management/employees/search',
    EMPLOYEE_RESTORE: (id: string) => `employee-management/employees/${id}/restore`,
    EMPLOYEE_RESIGN: (id: string) => `employee-management/employees/${id}/resigned`,
  },
  MASTER_DATA: {
    POSITION: 'master-payroll/positions',
    POSITION_BY_ID: (id: string) => `master-payroll/positions/${id}`,
    LEVEL: 'master-payroll/levels',
    LEVEL_BY_ID: (id: string) => `master-payroll/levels/${id}`,
    LEVEL_SEARCH: 'master-payroll/levels/search',
    LEVEL_TYPE_SEARCH: 'master-payroll/level-types',
    DIVISION_SEARCH: 'master-payroll/divisions/search',
    POSITION_SEARCH: 'master-payroll/positions/search',
    STRUCTURAL_SEARCH: 'master-payroll/structural/search',
  },
  PAYROLL_MGMT: {
    COMPONENTS: 'payroll-component/components',
    COMPONENTS_BY_ID: (id: string) => `payroll-component/components/${id}`,
    COMPONENT_TYPE_SEARCH: 'payroll-component/component-types/search',
    CUT_OFF_PERIOD: 'payroll-component/cut-off-period',
  },
  PAYROLLS: {
    DOWNLOAD: 'payroll-data/download-template',
    EMPLOYEES: 'payroll-data/employees',
    EMPLOYEE_BY_ID: (id: string) => `payroll-data/employees/${id}`,
    EMPLOYEE_COMPONENT: (id: string) => `payroll-data/employees/${id}/component`,
    EMPLOYEE_SET_EXPIRED: (id: string) => `payroll-data/employees/${id}/set-component-expired`,
    MASS_CHANGES: 'payroll-data/mass-changes',
    IMPORT: 'payroll-data/import',
    IMPORT_EXACT: 'payroll-data/import-exact',
    COMPONENT_SEARCH: 'payroll-data/component/search',
    COMPONENT_TYPE_SEARCH: 'payroll-data/component-types/search',
    EMPLOYEE_SEARCH: 'payroll-data/employees/search',
  },
  OVERTIME_EXPENSES: {
    OVERTIME: 'overtime-expense-management/overtime-expenses',
    OVERTIME_BULK: 'overtime-expense-management/overtime-expenses/bulk',
    OVERTIME_BY_ID: (id: string) => `overtime-expense-management/overtime-expenses/${id}`,
    CHECK_AMOUNT: 'overtime-expense-management/overtime-expenses/check-amount',
    PROJECTS_SEARCH: 'overtime-expense-management/projects/search',
    TEAMS_SEARCH: 'overtime-expense-management/teams/search',
    EMPLOYEE_SEARCH: 'overtime-expense-management/employees/search',
  },
  BUDGET_SETTING_MGMT: {
    BUDGET_SETTING: 'budget-setting-management/budget-settings',
    BUDGET_SETTING_BY_ID: (id: string) => `budget-setting-management/budget-settings/${id}`,
    PROJECT_SEARCH: 'budget-setting-management/projects/search',
  },
  ONSITE_MGMT: {
    ONSITE: 'onsite-expense-management/onsite-expenses',
    ONSITE_BY_ID: (id: string) => `onsite-expense-management/onsite-expenses/${id}`,
    CHECK_AMOUNT: 'onsite-expense-management/onsite-expenses/check-amount',
    PROJECT_SEARCH: 'onsite-expense-management/projects/search',
    EMPLOYEE_SEARCH: 'onsite-expense-management/employees/search',
  },
  DISBURSEMENT_MGMT: {
    COMPONENT_EDIT: (id: string) => `run-payroll/payrolls/${id}/component`,
    COMPONENT_EXISTING: (id: string) => `run-payroll/componentExisting/${id}`,
    COMPONENT_SEARCH: 'run-payroll/Components/search',
    CSV_DATA: (id: string) => `run-payroll/payrolls/csv/${id}`,
    CUT_OFF_PERIOD: 'run-payroll/payrolls/cutoffperiod',
    DIVISION_SEARCH: 'run-payroll/divisions/search',
    EMPLOYEES_SEARCH: 'run-payroll/employees/search',
    EMPLOYEE_EXISTING: (id: string) => `run-payroll/employeeExisting/${id}`,
    LIST_EMPLOYEE_BY_ID: (id: string) => `run-payroll/payrolls/${id}/employees`,
    PAYROLL: 'run-payroll/payrolls',
    PAYROLL_SETUP: 'run-payroll/payrolls/setup',
    POSITION_SEARCH: 'run-payroll/positions/search',
    PROJECT_SEARCH: 'run-payroll/project/search',
    RESTORE_COMPONENT: (id: string) => `run-payroll/payrolls/${id}/restorecomponent`,
    RUN_PAYROLL_BY_ID: (id: string) => `run-payroll/payrolls/${id}`,
    RUN_PAYROLL_EMPLOYEE: (id: string, employeeId: string) => `run-payroll/payrolls/${id}/employees/${employeeId}`,
    SAVE_RUN_PAYROLL: (id: string) => `run-payroll/payrolls/${id}/done`,
    STRUCTURAL_SEARCH: 'run-payroll/structural/search',
    UPDATE_EDIT_EMPLOYEE: (id: string, componentId: string, employeeId: string) => `run-payroll/payrolls/update-employees?PayrollDisbursementId=${id}&PayrollDisbursementItemId=${componentId}&EmployeeId=${employeeId}`,
    WIDGET_SUMMARY: (id: string) => `run-payroll/payrolls/${id}/summary`,
  },
  RUN_THR_MGMT: {
    RUN_THR: 'run-holiday-allowance/holiday-allowances',
    RUN_THR_BY_ID: (id: string) => `run-holiday-allowance/holiday-allowances/${id}`,
    RUN_THR_EMPLOYEE_BY_ID: (id: string) => `run-holiday-allowance/holiday-allowances/${id}/employee`,
    RUN_THR_WIDGET: (id: string) => `run-holiday-allowance/holiday-allowances/${id}/employee-summary`,
    SELECT_EMPLOYEES: (id: string) => `run-holiday-allowance/holiday-allowances/${id}/employees`,
    EMPLOYEES_SEARCH: 'run-holiday-allowance/holiday-allowances/employees/search',
    CSV_RUN_THR: (id: string) => `run-holiday-allowance/holiday-allowances/${id}/report`,
    SAVE_RUN_THR: (id: string) => `run-holiday-allowance/holiday-allowances/${id}/complated`,
    COMPONENT_EMPLOYEE: (id: string) => `run-holiday-allowance/holiday-allowances/employee/${id}/components`,
    COMPONENT_RESTORE: (id: string) => `run-holiday-allowance/holiday-allowances/employee/${id}/component-restore`,
  },
  CALENDAR_MGMT: {
    CALENDAR: 'calendar-management/calendar',
    CALENDAR_BY_ID: (id: string) => `calendar-management/calendar/${id}`,
  },
  PAYSLIP_MGMT: {
    PAYSLIP: '/payroll/payslip',
    EMPLOYEE_LIST_BY_ID: (id: string) => `payroll/payslip/employee/${id}`,
    PAYSLIP_DATA: (id: string, employeeId: string) => `payroll/payslip/${id}/employee/${employeeId}`,
    SEND_EMAIL_BY_ID: () => '/payslip/send-email',
  },
  REIMBURSEMENT: {
    REIMBURSE_COMPONENT: {
      COMPONENT: 'reimburse-component/components',
      BY_ID: (id: string) => `reimburse-component/components/${id}`,
    },
    REIMBURSE_SETTINGS: {
      SETTINGS: 'reimburse-setting/reimburse-settings',
      TYPES: 'reimburse-setting/reimburse-settings/types/search',
      CATEGORIES: 'reimburse-setting/reimburse-settings/categories/search',
      BY_ID: (id: string) => `reimburse-setting/reimburse-settings/${id}`,
      EMPLOYEE_SEARCH: 'reimburse-setting/reimburse-settings/employees/search',
      PROJECT_SEARCH: 'reimburse-setting/reimburse-settings/projects/search',
    },
  },
  PAYROLL_DASHBOARD: {
    SUMMARY: '/payroll-dashboard/payrolls/current-year',
    EMPLOYMENT_STATUS: '/payroll-dashboard/payrolls/employment-status',
    HOLIDAY_ALLOWANCE: '/payroll-dashboard/payrolls/holiday-allowance',
    DISBURSEMENT: '/payroll-dashboard/payrolls/disbursement',
    OVERTIME: '/payroll-dashboard/payrolls/overtime',
    ONSITE_INCENTIVE: '/payroll-dashboard/payrolls/onsite-incentive',
    UPCOMING_PAYROLL: '/payroll-dashboard/payrolls/upcoming-next-payroll',
  },
} as const;
