trigger:
  tags:
      include:
        - apps/payroll/v*
      exclude:
        - apps/payroll/v*-*
  paths:
    include:
      - applications/payroll.webapp

pr: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: Docker@2
    inputs:
      containerRegistry: 'docker connection'
      repository: 'devradyalabs / internal-apps'
      command: 'buildAndPush'
      Dockerfile: 'applications/payroll.webapp/docker/production/Dockerfile'
      buildContext: 'applications/payroll.webapp'
      tags: 'cms-prod'
