import { formatDate } from '@/utils';

import type { Employee } from '../../types/employee';

const employeeNormalizer = (data: Employee): Employee => ({
  employeeId: data.employeeId || '',
  employeeIdNumber: data.employeeIdNumber || '',
  firstName: data.firstName || '',
  lastName: data.lastName || '',
  fullname: data.fullname || '',
  divisionId: data.divisionId || '',
  divisionName: data.divisionName || '',
  levelId: data.levelId || '',
  levelName: data.levelName || '',
  emailAddress: data.emailAddress || '',
  employmentStatusId: data.employmentStatusId || '',
  employmentStatusName: data.employmentStatusName || '',
  position: data.position || 0,
  positionId: data.positionId || '',
  positionName: data.positionName || '',
  citizenIdNumber: data.citizenIdNumber || '',
  address: data.address || '',
  residentialAddress: data.residentialAddress || '',
  placeOfBirth: data.placeOfBirth || '',
  dateOfBirth: data.dateOfBirth ? formatDate(data.dateOfBirth) : '',
  mobilePhone: data.mobilePhone || '',
  gender: data.gender || '',
  maritalStatus: data.maritalStatus || '',
  religion: data.religion || '',
  organizationId: data.organizationId || '',
  organizationName: data.organizationName || '',
  structuralId: data.structuralId || '',
  structuralName: data.structuralName || '',
  joinDate: data.joinDate ? formatDate(data.joinDate) : '',
  signDate: data.signDate ? formatDate(data.signDate) : '',
  endDate: data.endDate ? formatDate(data.endDate) : '',
  npwpNumber: data.npwpNumber || '',
  latestNpwpNumber: data.latestNpwpNumber || '',
  ptkpStatus: data.ptkpStatus || '',
  bankName: data.bankName || '',
  bankCode: data.bankCode || '',
  bankAccountNumber: data.bankAccountNumber || '',
  bankAccountHolderName: data.bankAccountHolderName || '',
  bpjsTkNumber: data.bpjsTkNumber || '',
  bpjsKesNumber: data.bpjsKesNumber || '',
  createdBy: data.createdBy || '',
  createdByFullName: data.createdByFullName || '',
  createdAt: data.createdAt ? formatDate(data.createdAt) : '',
  lastUpdatedBy: data.lastUpdatedBy || '',
  lastUpdatedByFullName: data.lastUpdatedByFullName || '',
  lastUpdatedAt: data.lastUpdatedAt ? formatDate(data.lastUpdatedAt) : '',
  approvalLines: data.approvalLines.map((line) => ({
    rule: line.rule,
    employeeApprovals: line.employeeApprovals,
  })),
});

export default employeeNormalizer;
