#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

filechanged=$(git diff --cached --numstat "applications/payroll.webapp" | wc -l)

echo "filechanged  --> $filechanged"
if [ $filechanged != "0" ]
then
  cd applications/payroll.webapp || exit
  pnpm commitlint --edit "$1"
else
  exit 0
fi
